### PR TITLE
Fix clang-win.jam so that it works

### PR DESCRIPTION
**Pull request by pdimov**

### CODE REVIEW

**Comment by pdimov** [comment]
Fixes #330.

**Comment by pdimov** [comment]
With this in place, clang-cl should now be usable on Appveyor (which has it installed and in PATH), by just using `toolset=clang-win`.

**Comment by eldiener** [comment]
The new clang-win.jam worked well. Is there a way to choose a VC++ version as the backend headers and libraries, or is the latest VC++ version found always chosen ? The old clang-win had a <compatibility> property but the new one does not have anything like that which I can see.

**Comment by pdimov** [comment]
I'm not sure how `clang-cl` picks the version to use. Will need to check the sources. I think that if you invoke it from a developer command prompt, it uses whatever is set by it, but if not, it scans and picks the most recent MSVC toolset (and Windows SDK - these two are separate.)

**Pull request merged**
