### PR TITLE
Provide error message and stacktrace with bad parameter to bjam.call()

### PR DESCRIPTION
**Pull request by frenchtoast747**
The previous implementation would just die when a bad parameter was passed in to `bjam.call()`.

This tries to provide an error message describing the value that was invalid and falls back to just a TypeError in the event that `repr()` cannot be called on the PyObject. Both provide a stacktrace to where the call failed.

### CODE REVIEW

**Comment by frenchtoast747** [comment]
Should the Engine's version be updated when changes are made?

**Comment by swatanabe** [comment]
AMDG

On 10/29/2015 08:28 AM, Aaron Boman wrote:
> Should the Engine's version be updated when changes are made?
> 

  I only change the engine version for
changes that can cause incompatibility.
e.g. adding a builtin, significant
bug fixes, etc.  This change seems
purely cosmetic.

In Christ,
Steven Watanabe

**Comment by frenchtoast747** [comment]
Alright, thanks!

**Comment by vprus** [comment]
Aaron,

thanks for the patch, cherry-picked.

**Pull request closed without merging**
