### PR TITLE
Prevent vcvarsall.bat from changing current directory

### PR DESCRIPTION
**Pull request by hia3**
Building with VS2017 15.3.5 produces following error:

c1: fatal error C1083: Cannot open source file: 'yyacc.c': No such file or directory

This happens because vsdevcmd_end.bat changes current directory to %USERPROFILE%\Source if it exists.

### CODE REVIEW

**Comment by hia3** [comment]
Here is what vsdevcmd_end.bat does:

    @REM Set the current directory that users will be set after the script completes
    @REM in the following order:
    @REM 1. [VSCMD_START_DIR] will be used if specified in the user environment
    @REM 2. [USERPROFILE]\source if it exists
    @REM 3. current directory
    if "%VSCMD_START_DIR%" NEQ "" (
        cd /d "%VSCMD_START_DIR%"
    ) else (
        if EXIST "%USERPROFILE%\Source" (
            cd /d "%USERPROFILE%\Source"
        )
    )

**Comment by pdimov** [comment]
Why has this been closed?

**Comment by pdimov** [comment]
This problem has just been reported against 1.66 beta 1 RC 1: https://lists.boost.org/Archives/boost/2017/11/239824.php

**Comment by hia3** [comment]
> Why has this been closed?
I wasn't sure why this patch works. Feel free to apply it.

**Comment by hia3** [comment]
Simple `pushd .` is enough, no need for %CD%

**Comment by pdimov** [comment]
Yes, I was going to say the same thing.

**Comment by jhunold** [comment]
Created an edited version on #263. Will merge to develop as soon as CI passes.

**Pull request closed without merging**
