### PR TITLE
Remove unused mips revision

### PR DESCRIPTION
**Pull request by wzssyqa**
There are several mips revision:
  'mips1', 'mips2', 'mips3', 'mips4', 'mips32', 'mips32r2', 'mips64'.
while in fact only mips1 is used, so remove other ones.
And, mips1 in fact is used for all MIPS revisions.

Then rename mips1 to mips.

### CODE REVIEW

**Comment by wzssyqa** [comment]
https://github.com/boostorg/context/pull/93
is sub-PR of this PR

**Comment by wzssyqa** [comment]
https://github.com/boostorg/log/pull/155
is sub-PR for `log`.

**Comment by wzssyqa** [comment]
https://github.com/boostorg/config/pull/389
is the sub-PR for `config`.

**Comment by wzssyqa** [comment]
https://github.com/boostorg/boost/pull/540
is the sub-PR for `boost`.

**Review by Kojoley — COMMENTED** [review]
You should not remove `mips1` straight away if there is a code that depends on it (is not it an obvious thing?). Why not simply add `mips` without removing `mips*`?

Also, B2 development has moved to https://github.com/bfgroup/b2. You need to open PR there.

**Comment by wzssyqa** [comment]
@Kojoley thanks for your instruction: https://github.com/bfgroup/b2/pull/58

**Pull request closed without merging**
