### PR TITLE
Refactoring conditional directives for incomplete if conditions.

### PR DESCRIPTION
**Pull request by wmarquesr**
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.

* [Linux kernel coding style](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892)
* [Living in the #ifdef Hell](https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/)

It might improve code understanding, maintainability and error-proneness.

### CODE REVIEW

**Comment by vprus** [comment]
Thanks for your patch, it has been cherry-picked.

**Comment by wmarquesr** [comment]
Right, but why refused ?

**Comment by vprus** [comment]
Apparently, the mouse has slipped, the code is in. Sorry for confusion.

**Comment by wmarquesr** [comment]
Oh, right. So you agree with that kind of refactoring ?

**Comment by vprus** [comment]
Yes, this refactoring makes code cleaner.

Just to clear up any possible confusion - your code is on develop branch now, see: https://github.com/boostorg/build/commits/develop

Git has two ways to process pull requests - "merge", which GitHub shows as "merged", and "cherry-pick", which GitHub shows as "closed". However, in both cases your code is on the development branch, in exactly the same state.

Thanks again for your contribution!

**Pull request closed without merging**
