### PR TITLE
Python.jam: Postpone the computation of python "major-minor" version …

### PR DESCRIPTION
**Pull request by raffienficiaud**
Following up my post on the ML: this fixes the issue I was having for not being able to build boost.python.

The PR is based on master branch. Included some tabs to space conversion.

### CODE REVIEW

**Comment by raffienficiaud** [comment]
Note that I do not know bjam much, and do not know what the line ``version = $(major-minor:J=.) ;`` is doing. Might be an issue as it is not rewritten at the beginning of the function.

**Comment by raffienficiaud** [comment]
Thanks!

**Comment by sav-ix** [comment]
Thank you for fix! It works fine.

**Comment by stefanseefeld** [comment]
Would someone please merge this to master ? (Alternatively, I may do it if no-one objects. I got confirmation from a Boost.Python user that it fixes their build issue, too.)

**Comment by stefanseefeld** [comment]
Oh, excellent. Thanks !

**Comment by raffienficiaud** [comment]
@sav-ix glad to hear :)
@grafikrobot Thanks Rene!

**Pull request merged**
