### PR TITLE
Allow linking for gcc/mingw and clang targeting gcc on Windows to use response files to mitigate Windows command line limitations.

### PR DESCRIPTION
**Pull request by eldiener**

### CODE REVIEW

**Comment by eldiener** [comment]
In the tests I see a failed link when cross-linking from Windows to Linux but I do not see in the tests any output which gives a reason for the failed link. Therefore it is impossible to determine what is wrong with my PR, which looks correct to me.

**Comment by eldiener** [comment]
The problem for the toolset_clang_linux test, when run on Windows, is that the default clang on Windows target triple '-target' parameter when running a 64-bit compile is 'x86_64-pc-windows-msvc' and when running a 32-bit compile is 'i386-pc-windows-msvc '.  In other words the clang implementation on Windows defaults to targeting VC++ and not gcc, while the clang-linux.jam file is for linux, usually targeting gcc. The correct target triples for targeting gcc are 'x86_64-pc-windows-gnu' and 'i686-pc-windows-gnu'. But the clang-linux.jam does not attempt to set this correct target under Windows. Maybe it should be doing that but it never has, and I did not write the original clang-linux.jam file. Nor has my PR changed that aspect of the jam file at all. Of course on Linux the default target triple is for gcc, not msvc, so no target triple needs to be specified 

What is happening when the target triple is targeting vc++ on Windows is that when a linker line has '-Wl,-soname -Wl,libl1.so'. the -soname option is ignored and the linker then looks for 'libl1.so' as a source, which of course does not exist and it fails. Also of course stuff like '-Wl,--start-group -Wl,-Bstatic  -Wl,-Bdynamic  -Wl,--end-group' it also ignores. With the correct target triple it knows what all this means.

The only thing I am wondering is why this test_clang_linux test ever worked on Windows !!!

**Comment by eldiener** [comment]
Please ignore the previous comment. Here is the actual issue, which is a Boost Build test system bug:

If I add a response file to a command in the clang-linux.jam file the Boost Build test system test 'toolset_clang_linux' will give an error, despite the fact that response files are fully supported by clang. For instance with these lines in the current clang-linux.jam on the 'develop' branch:

```
actions link bind LIBRARIES {
   "$(CONFIG_COMMAND)" -L"$(LINKPATH)" -Wl,-R$(SPACE)-Wl,"$(RPATH)" -Wl,-rpath-link$(SPACE)-Wl,"$(RPATH_LINK)" -o "$(<)" $(START-GROUP) "$(>)" "$(LIBRARIES)" $(FINDLIBS-ST-PFX) -l$(FINDLIBS-ST) $(FINDLIBS-SA-PFX) -l$(FINDLIBS-SA) $(END-GROUP) $(OPTIONS) USER_OPTIONS)
}
```

replaced by:

```
actions link bind LIBRARIES {
  "$(CONFIG_COMMAND)" -L"$(LINKPATH)" -Wl,-R$(SPACE)-Wl,"$(RPATH)" -Wl,-rpath-link$(SPACE)-Wl,"$(RPATH_LINK)" -o "$(<)" $(START-GROUP) "$(>)" "$(LIBRARIES)" $(FINDLIBS-ST-PFX) -l$(FINDLIBS-ST) $(FINDLIBS-SA-PFX) -l$(FINDLIBS-SA) $(END-GROUP) @"@($(<[1]).rsp:E=$(OPTIONS))" $(USER_OPTIONS)
}
```

the Boost Build test system when running the 'toolset_clang_linux' will err with:

```
file bin\clang-linux-3.9.0\debug\target-os-linux\test.rsp
-fPIC -g
clang-linux.link bin\clang-linux-3.9.0\debug\target-os-linux\test

  "C:\Utilities\python\x64\2.7.16\python.exe" "C:\Users\eldnew8\AppData\Local\Temp\tmplhdgla/src/clang-linux-3.9.0.py"  -Wl,-R -Wl,"C:\Users\eldnew8\AppData\Local\Temp\tmplhdgla\bin\clang-linux-3.9.0\debug\target-os-linux" -Wl,-rpath-link -Wl,"C:\Users\eldnew8\AppData\Local\Temp\tmplhdgla\bin\clang-linux-3.9.0\debug\target-os-linux" -o "bin\clang-linux-3.9.0\debug\target-os-linux\test" -Wl,--start-group "bin\clang-linux-3.9.0\debug\target-os-linux\main.o" "bin\clang-linux-3.9.0\debug\target-os-linux\libl1.so"  -Wl,-Bstatic  -Wl,-Bdynamic  -Wl,--end-group @"bin\clang-linux-3.9.0\debug\target-os-linux\test.rsp"
['clang++', '-Wl,-R', '-Wl,C:\\Users\\eldnew8\\AppData\\Local\\Temp\\tmplhdgla\\bin\\clang-linux-3.9.0\\debug\\target-os-linux', '-Wl,-rpath-link', '-Wl,C:\\Users\\eldnew8\\AppData\\Local\\Temp\\tmplhdgla\\bin\\clang-linux-3.9.0\\debug\\target-os-linux', '-o', 'bin\\clang-linux-3.9.0\\debug\\target-os-linux\\test', '-Wl,--start-group', 'bin\\clang-linux-3.9.0\\debug\\target-os-linux\\main.o', 'bin\\clang-linux-3.9.0\\debug\\target-os-linux\\libl1.so', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-Wl,--end-group', '@bin\\clang-linux-3.9.0\\debug\\target-os-linux\\test.rsp']
...failed clang-linux.link bin\clang-linux-3.9.0\debug\target-os-linux\test...
...failed updating 1 target...
...updated 7 targets...

}}}
STDERR {{{

}}}

*** Copying the state of working dir into 'failed_test' ***

The failed command was:
b2 -sBOOST_BUILD_PATH="E:\Programming\VersionControl\modular-boost\tools\build\test/.." --user-config= -sPYTHON_CMD=C:\Utilities\python\x64\2.7.16\python.exe target-os=linux -j1 -d2 toolset=clang-linux-3.9.0 --test-config="E:\Programming\VersionControl\modular-boost\tools\build\test\test-config.jam"
stacktrace {{{
at line 608 of E:\Programming\VersionControl\modular-boost\tools\build\test\BoostBuild.py (fail_test)
    from line 497 of E:\Programming\VersionControl\modular-boost\tools\build\test\BoostBuild.py (run_build_system)
    from line 110 of E:\Programming\VersionControl\modular-boost\tools\build\test\TestToolset.py (test_toolset)
    from line 19 of toolset_clang_linux.py (<module>)

}}}
```

I am trying in this PR to add response files to the linking actions in clang-linux.jam file when run on Windows because Windows has a line length limit which is exceeded by certain tests in a few Boost libraries.

Would someone familiar with the Boost Build test system look at this issue and try to fix the test system so that response files in the clang-linux.jam file pass the 'toolset_clang_linux' test please ? I know the Boost Build test system is largely Python with a little C++ thrown in, and I do understand Python, but the design is pretty clever and intricate stuff and it would be nice if the original developer(s) could fix this "bug" in the test system so that users of clang-linux under Windows could run library tests without failing because the command line is too long.

Once the Boost Build test system is fixed this PR will pass all its tests.

Thank you !

**Comment by eldiener** [comment]
Any objections merging this to 'develop' ?

**Comment by eldiener** [comment]
No problem, I did not mean to push this issue other than just to get an acknowledgment that it exists. Steve's Python code is fairly complicated and I just did not have the patience to try to follow it and see how this could be fixed. My impression is just that his code did not take into account the idea that a part of a command could be a generated file expansion. Maybe something along the lines of before his code validates a command it needs to expand the command by recursively inserting whatever is in any generated file expansions into the actual command being examined. Then he can use his code as it now is to validate. I just could not figure out where in the Python code he is actually reading in a command line, before validating it.

**Comment by Kojoley** [comment]
I use clang-win toolset and I did not hit the limit even a single time. Could response files be used only when the limit is actually reached? I really hate to not see passed command line options when a build fails.

**Comment by eldiener** [comment]
The limit is reached on Windows during certain multiprecision tests. You can use the -d2 option to show the contents of response files.

**Comment by Kojoley** [comment]
> You can use the -d2 option to show the contents of response files.

Well it is a workaround for a workaround and I cannot control everyones CI to add it when I need it.

Not to mention that response file strategy taxes build time because filesystem access syscalls are terribly slow on Windows.

**Comment by eldiener** [comment]
> 
> 
> > You can use the -d2 option to show the contents of response files.
> 
> Well it is a workaround for a workaround and I cannot control everyones CI to add it when I need it.
> 
> Not to mention that response file strategy taxes build time because filesystem access syscalls are terribly slow on Windows.

The msvc.jam file for vc++ use response files extensively in their actions. It was my choice to use response files for clang-linux.jam just on Windows, where gcc is targeted, but Rene wants it used on all platforms in order to pass the toolset-clang-linux.py test, which he had to update to fix the test. Certain tests on Windows will fail because the command line can run too long, and the response files solve that problem. I do not know what else to say. Is it better to have the tests fail on Winoews because the command line is too long ? I do not think so.

**Comment by eldiener** [comment]
> 
> 
> > You can use the -d2 option to show the contents of response files.
> 
> Well it is a workaround for a workaround and I cannot control everyones CI to add it when I need it.
> 
> Not to mention that response file strategy taxes build time because filesystem access syscalls are terribly slow on Windows.

The clang-win.jam file uses response files also, since it inherits its actions from msvc.jam.

**Comment by eldiener** [comment]
> 
> 
> So.. took a bit of work. But I have something working. Here's the deal...
> 
> I did a bunch of changes to the current tests:
> [7d98662](https://github.com/boostorg/build/commit/7d9866256d1ce46abaf8355bb618cdebab9cfe62)
> 
> With that you would need to apply the response file change generically to all clang-linux variants:
> https://gist.github.com/grafikrobot/5fa43cfeb21a8f6ae80247c434c1cbe3
> 
> And to deal with that you also need to change the test for clang-linux:
> https://gist.github.com/grafikrobot/4e13de3fbe42c30db3c16a85b25d8c1e

I am still seeing a failure with the toolset_clang_linux.py test when I test it locally on Windows 10 with the files above and the latest 'develop' changes which incorporate your other changes for allowing generated file expansion.

**Comment by eldiener** [comment]
> 
> 
> > I am still seeing a failure with the toolset_clang_linux.py test when I test it locally on Windows 10 with the files above and the latest 'develop' changes which incorporate your other changes for allowing generated file expansion.
> 
> Can you add the changes to the PR so I can see how CI behaves?

They should all be there now.

**Comment by eldiener** [comment]
Is there still an intention to fix the tests so that generated file expansion works with the toolset_clang_linux test ?

**Comment by eldiener** [comment]
I merged the PR. It is totally valid. If you find something invalid about it please mention it.

**Comment by Kojoley** [comment]
> I merged the PR. It is totally valid. If you find something invalid about it please mention it.

You made clang-linux use rsp files on Linux for no reason. Also, toolset_clang_linux test now tests nothing, all flags are now in a rsp file and you are not testing it.

**Comment by eldiener** [comment]
Talk to Renee, not me.

**Comment by Kojoley** [comment]
Why I should talk to Renee if you authored and self-merged the PR?

**Comment by eldiener** [comment]
Because Renee is the person who supplied the "fix" for the toolset_clang_linux test and specified that response files should be used on all platforms for clang-linux.jam so that the test would pass. I submitted a perfectly valid PR a long while back, which used response files for clang-linux.jam on Windows because of the limitations of the Windows command line length.

**Comment by Kojoley** [comment]
But you had merged the PR.

> which used response files for clang-linux.jam on Windows

It uses rsp files on **Linux** after this PR too.

**Comment by Kojoley** [comment]
I wished the rsp cancer go away, instead now we have it everywhere because someone somehow did not fit a command into thousands of chars (into 8k?).

**Comment by eldiener** [comment]
I can change the clang-linux.jam, Rene, so that when the link command is executed on Windows it uses response files whereas when the link command is executed in another OS it does not use response files. Will the toolset_clang_linux test pass with that change no matter on what OS it is tested on ?

**Pull request merged**
