### PR TITLE
Revert "Allow linking for gcc/mingw and clang targeting gcc on Windows to use response files to mitigate Windows command line limitations."

### PR DESCRIPTION
**Pull request by Kojoley**
Reverts boostorg/build#567

The PR introduced unjustified response files usage on Linux platform.

### CODE REVIEW

**Comment by eldiener** [comment]
Please do not revert this change. There are fixes in it that have nothing to do with response files, and support for response files, which are part of nearly all compilers, should be a part of Boost Build.

**Comment by eldiener** [comment]
Why are we reverting the response file changes ? Are not response files valid with all the compilers for which the changes apply ? Why are we deciding that response files should not be part of clang-linux.jam when clang fully supports them. They are needed for Windows, where the command line length is limited. What is it about response files that they are deemed wrong to use ?

**Comment by eldiener** [comment]
What is broken is that without a response file Windows commands can exceed their limit and therefore fail. I have already encountered this testing some libraries, with clang-linux on Windows targeting gcc. I think you know that msvc.jam has used response files forever. So I really do not understand the issue of using response files. If you like I can change clang-linux.jam to use response files under Windows but not otherwise.

**Comment by Kojoley** [comment]
> What is broken

The idea that anyone has to use the workaround while only some situation needs it is broken. My drive also becomes broken faster than it should.

> I think you know that msvc.jam has used response files forever.

This is one of the reasons why Boost.Build on Windows is so much slower since forever.

Revert this until you make Boost.Build not using response files until the actual limit is exceeded.

**Comment by eldiener** [comment]
I still do not understand what you want. Are you saying that for clang-linux.jam you do not want to use response files, or are you saying that Boost Build is going to remove response file support for all compilers. I can assert absolutely that I have already run into situations, using clang-linux.jam on Windows, where the lack of response files meant that the command line generated by some libraries exceeds the maximum 8k command line which Windows allows. Is there any problem keeping response files for clang-linux.jam on Windows only, since it is on Windows that some libraries fail tests because the command line exceeds 8k ? If there is please explain what the problem is.

**Comment by Kojoley** [comment]
Take a look:
```
> grep -E "(clang-win|mingw)" -R libs --include "*.yml" --include "*.yaml"
libs/accumulators/appveyor.yml:      PATH: C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%
libs/accumulators/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/accumulators/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/algorithm/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/algorithm/appveyor.yml:      PATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/align/.appveyor.yml:      TOOLSET: clang-win
libs/any/test/appveyor.yml:      TOOLSET: msvc-14.1,clang-win
libs/any/test/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/any/test/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/assert/appveyor.yml:      TOOLSET: msvc-14.1,clang-win
libs/assign/appveyor.yml:    - FLAVOR: mingw32
libs/assign/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/assign/appveyor.yml:    - FLAVOR: mingw64
libs/assign/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/atomic/appveyor.yml:    - TOOLSET: clang-win
libs/atomic/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
libs/atomic/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
libs/atomic/appveyor.yml:    - TOOLSET: clang-win
libs/atomic/appveyor.yml:      ADDPATH: C:\mingw\bin
libs/atomic/appveyor.yml:      ADDPATH: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
libs/bind/appveyor.yml:      TOOLSET: msvc-14.1,clang-win
libs/bind/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/bind/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/concept_check/appveyor.yml:    - FLAVOR: mingw32
libs/concept_check/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/concept_check/appveyor.yml:    - FLAVOR: mingw64
libs/concept_check/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/config/appveyor.yml:      ARGS: --toolset=clang-win address-model=64
libs/config/appveyor.yml:      ARGS: --toolset=clang-win address-model=32
libs/config/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/config/appveyor.yml:      PATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/contract/appveyor.yml:    - FLAVOR: mingw32
libs/contract/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/contract/appveyor.yml:    - FLAVOR: mingw64
libs/contract/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/conversion/test/appveyor.yml:      TOOLSET: msvc-14.1,clang-win
libs/conversion/test/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/conversion/test/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/core/appveyor.yml:    # clang-win 32 bit fails to link with "unable to load mspdbcore.dll (error code: 126)"
libs/core/appveyor.yml:      TOOLSET: clang-win
libs/core/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/core/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/core/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/crc/appveyor.yml:      TOOLSET: clang-win
libs/date_time/appveyor.yml:      B2_TOOLSET: clang-win
libs/date_time/appveyor.yml:    - FLAVOR: mingw32
libs/date_time/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/date_time/appveyor.yml:    - FLAVOR: mingw64
libs/date_time/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/dll/test/appveyor.yml:      TOOLSET: clang-win
libs/dll/test/appveyor.yml:      TOOLSET: clang-win
libs/dll/test/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/dll/test/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/dynamic_bitset/appveyor.yml:      B2_TOOLSET: clang-win
libs/dynamic_bitset/appveyor.yml:    - FLAVOR: mingw32
libs/dynamic_bitset/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/dynamic_bitset/appveyor.yml:    - FLAVOR: mingw64
libs/dynamic_bitset/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/endian/appveyor.yml:      TOOLSET: msvc-14.1,clang-win
libs/endian/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/endian/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/exception/appveyor.yml:      TOOLSET: clang-win
libs/exception/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/exception/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/filesystem/appveyor.yml:# clang-win fails to link the library
libs/filesystem/appveyor.yml:#    - TOOLSET: clang-win
libs/filesystem/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/filesystem/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/filesystem/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;
libs/format/appveyor.yml:      B2_TOOLSET: clang-win
libs/format/appveyor.yml:    - FLAVOR: mingw32
libs/format/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/format/appveyor.yml:    - FLAVOR: mingw64
libs/format/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/function/appveyor.yml:      TOOLSET: clang-win
libs/function/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/function/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/functional/.appveyor.yml:      TOOLSET: clang-win
libs/fusion/appveyor.yml:      TOOLSET: clang-win
libs/fusion/appveyor.yml:      TOOLSET: clang-win
libs/graph/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/graph/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/graph/appveyor.yml:      PATH: C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%
libs/integer/appveyor.yml:    - TOOLSET: clang-win
libs/integer/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/integer/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/integer/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;
libs/io/.appveyor.yml:      TOOLSET: clang-win
libs/iostreams/appveyor.yml:      B2_TOOLSET: clang-win
libs/iostreams/appveyor.yml:    - FLAVOR: mingw32
libs/iostreams/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/iostreams/appveyor.yml:    - FLAVOR: mingw64
libs/iostreams/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/iterator/appveyor.yml:    - TOOLSET: clang-win
libs/iterator/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/iterator/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/iterator/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;
libs/lockfree/appveyor.yml:  - TOOLSET: mingw-5
libs/lockfree/appveyor.yml:  - TOOLSET: mingw64-6
libs/lockfree/appveyor.yml:  - TOOLSET: mingw64-6
libs/lockfree/appveyor.yml:  - TOOLSET: mingw64-6
libs/log/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
libs/log/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
libs/log/appveyor.yml:      ADDPATH: C:\mingw\bin
libs/log/appveyor.yml:      ADDPATH: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
libs/logic/appveyor.yml:      B2_TOOLSET: clang-win
libs/logic/appveyor.yml:    - FLAVOR: mingw32
libs/logic/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/logic/appveyor.yml:    - FLAVOR: mingw64
libs/logic/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/math/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/math/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/math/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/math/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/math/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/math/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/math/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/math/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/math/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/math/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/move/appveyor.yml:    - FLAVOR: mingw32
libs/move/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/move/appveyor.yml:    - FLAVOR: mingw64
libs/move/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/mp11/appveyor.yml:      TOOLSET: msvc-14.1,clang-win
libs/mpl/appveyor.yml:    - FLAVOR: mingw32
libs/mpl/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/mpl/appveyor.yml:    - FLAVOR: mingw64
libs/mpl/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/multiprecision/appveyor.yml:      PATH: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH%
libs/multiprecision/appveyor.yml:      PATH: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH%
libs/multiprecision/appveyor.yml:      PATH: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH%
libs/multiprecision/appveyor.yml:      PATH: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH%
libs/multi_array/appveyor.yml:      TOOLSET: clang-win
libs/nowide/.appveyor.yml:      B2_TOOLSET: clang-win
libs/nowide/.appveyor.yml:    - FLAVOR: mingw32
libs/nowide/.appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/nowide/.appveyor.yml:    - FLAVOR: mingw64
libs/nowide/.appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/nowide/.github/workflows/ci_tests.yml:        [[ "${{matrix.generator}}" =~ "Unix" ]] && toolset=gcc || toolset=mingw
libs/nowide/.github/workflows/ci_tests.yml:        sed -i 's/mingw/gcc/' project-config.jam
libs/numeric/interval/appveyor.yml:    - FLAVOR: mingw32
libs/numeric/interval/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/numeric/interval/appveyor.yml:    - FLAVOR: mingw64
libs/numeric/interval/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/parameter/appveyor.yml:      PATH: C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%
libs/parameter/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/parameter/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/phoenix/appveyor.yml:      TOOLSET: clang-win
libs/phoenix/appveyor.yml:      TOOLSET: clang-win
libs/pool/appveyor.yml:    - FLAVOR: mingw32
libs/pool/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/pool/appveyor.yml:    - FLAVOR: mingw64
libs/pool/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/program_options/appveyor.yml:    - FLAVOR:  mingw32
libs/program_options/appveyor.yml:      SCRIPT:  ci\mingw.bat
libs/program_options/appveyor.yml:    - FLAVOR:  mingw64
libs/program_options/appveyor.yml:      SCRIPT:  ci\mingw.bat
libs/property_map/appveyor.yml:    - FLAVOR: mingw32
libs/property_map/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/property_map/appveyor.yml:    - FLAVOR: mingw64
libs/property_map/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/ptr_container/appveyor.yml:      B2_TOOLSET: clang-win
libs/ptr_container/appveyor.yml:    - FLAVOR: mingw32
libs/ptr_container/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/ptr_container/appveyor.yml:    - FLAVOR: mingw64
libs/ptr_container/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/rational/appveyor.yml:    - FLAVOR: mingw32
libs/rational/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/rational/appveyor.yml:    - FLAVOR: mingw64
libs/rational/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/regex/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/regex/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/regex/appveyor.yml:      PATH: C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%
libs/serialization/appveyor.yml:  - set PATH=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin;%CD%;%PATH%
libs/signals2/appveyor.yml:    - FLAVOR: mingw32
libs/signals2/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/signals2/appveyor.yml:    - FLAVOR: mingw64
libs/signals2/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/smart_ptr/appveyor.yml:      TOOLSET: clang-win
libs/smart_ptr/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/smart_ptr/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/spirit/.appveyor.yml:      Get-ChildItem -Path "$git\mingw64\*" -Include *.exe -Recurse |
libs/static_string/.appveyor.yml:      B2_TOOLSET: clang-win
libs/static_string/.appveyor.yml:    - FLAVOR: mingw32
libs/static_string/.appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/static_string/.appveyor.yml:    - FLAVOR: mingw64
libs/static_string/.appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/sync/appveyor.yml:    - TOOLSET: clang-win
libs/sync/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
libs/sync/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
libs/sync/appveyor.yml:    - TOOLSET: clang-win
libs/sync/appveyor.yml:      ADDPATH: C:\mingw\bin
libs/sync/appveyor.yml:      ADDPATH: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
libs/system/appveyor.yml:      TOOLSET: clang-win
libs/system/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/system/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/test/.appveyor.yml:      B2_TOOLSET: clang-win
libs/test/.appveyor.yml:    - FLAVOR: mingw32
libs/test/.appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/test/.appveyor.yml:    - FLAVOR: mingw64
libs/test/.appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/test/.appveyor.yml:    - FLAVOR: mingw64
libs/test/.appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/test/.appveyor.yml:    - FLAVOR: mingw64
libs/test/.appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/test/.appveyor.yml:    - FLAVOR: mingw64
libs/test/.appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/thread/appveyor.yml:    - ADDPATH: C:\mingw\bin;
libs/thread/appveyor.yml:# https://sourceforge.net/p/mingw-w64/bugs/694/
libs/thread/appveyor.yml:#    - ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/thread/appveyor.yml:#    - ADDPATH: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;
libs/throw_exception/appveyor.yml:      TOOLSET: clang-win
libs/throw_exception/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/throw_exception/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/timer/appveyor.yml:      TOOLSET: clang-win
libs/timer/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/timer/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/tokenizer/appveyor.yml:    - FLAVOR: mingw32
libs/tokenizer/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/tokenizer/appveyor.yml:    - FLAVOR: mingw64
libs/tokenizer/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/typeof/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/typeof/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/typeof/appveyor.yml:      PATH: C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%
libs/type_index/test/appveyor.yml:      TOOLSET: msvc-14.1,clang-win
libs/type_index/test/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/type_index/test/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/type_traits/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/type_traits/appveyor.yml:      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
libs/type_traits/appveyor.yml:      PATH: C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%
libs/units/appveyor.yml:    - COMMENT: mingw-w64 32-bit
libs/units/appveyor.yml:      ADDPATH: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw64\bin;
libs/units/appveyor.yml:    - COMMENT: mingw-w64 64-bit
libs/units/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/utility/appveyor.yml:    - TOOLSET: clang-win
libs/utility/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/utility/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/utility/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;
libs/uuid/appveyor.yml:      B2_TOOLSET: clang-win
libs/uuid/appveyor.yml:    - FLAVOR: mingw32
libs/uuid/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/uuid/appveyor.yml:    - FLAVOR: mingw64
libs/uuid/appveyor.yml:      SCRIPT: ci\appveyor\mingw.bat
libs/variant/test/appveyor.yml:      TOOLSET: msvc-14.1,clang-win
libs/variant/test/appveyor.yml:      ADDPATH: C:\mingw\bin;
libs/variant/test/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/variant2/appveyor.yml:      TOOLSET: clang-win
libs/wave/appveyor.yml:## cygwin and mingw disabled for now, failing to build
libs/wave/appveyor.yml:#      ADDPATH: C:\mingw\bin;
libs/wave/appveyor.yml:#      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;
libs/winapi/appveyor.yml:      ADDPATH: C:\mingw\bin
libs/winapi/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
libs/winapi/appveyor.yml:      ADDPATH: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
libs/winapi/appveyor.yml:      ADDPATH: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
```
Do you see why I do not like unconditional usage of response file workaround? All those libraries do not care about it, they are already running CI without hitting the limit. I also have not seen any post on mail list or issue on bug tracker. You are pushing downsides on everyone while majority will only get disadvantages of it, and certainly no one needs it on Linux.

**Comment by eldiener** [comment]
Your list above is meaningless. I have offered to change clang-linux.jam so that the response files is only used when building on Windows. It is totally idiotic to remove response files on Windows.

**Comment by eldiener** [comment]
If you have a means of using or nor using a response file based on a toolset configuration option I think that is great. I only ask that this is documented so that developers testing libraries can configure their toolsets so that failures regarding a command line that is too long can be solved by turning on the use of response files without having to change that toolset's jam file in any way.

**Comment by eldiener** [comment]
Where does the reference documentation for the dynamic response files reside ? it is not yet anywhere in https://boostorg.github.io/build/manual/master/index.html which I can find.

**Comment by eldiener** [comment]
I found where the developer pages for the manual reside.

**Pull request closed without merging**
