### PR TITLE
 Unify mips architectures

### PR DESCRIPTION
**Pull request by FlyGoat**

### CODE REVIEW

**Comment by FlyGoat** [comment]
These four PRs should be accepted together:
- https://github.com/boostorg/build/pull/375
- https://github.com/boostorg/config/pull/254
- https://github.com/boostorg/context/pull/93
- https://github.com/boostorg/log/pull/66

**Comment by FlyGoat** [comment]
> 1. Adding the general "mips" architecture without removing the rest. We would need to indicate they non-general as deprecated somehow.

Thanks for your suggestions, where should be the best place to add such a warning?

It would be better if these PRs can be accepted at once so that build the whole boost on mips won't be broken.

**Comment by Lastique** [comment]
@FlyGoat Is this no longer relevant? Should the other PRs be closed as well?

**Comment by FlyGoat** [comment]
@Lastique Sorry my fault, I'll rebase and reopen it. Yes, it's still a problem.

**Comment by FlyGoat** [comment]
@wzssyqa handed will sucess this PR.

**Pull request closed without merging**
