### PR TITLE
Print fopen fail reason

### PR DESCRIPTION
**Pull request by Kojoley**
Should help investigate #555

### CODE REVIEW

**Comment by Kojoley** [comment]
```
Actual STDERR {{{
[errno 2] failed to scan file 'dir\bin\hello1.cpp': No such file or directory
}}}
```

I tried to understand whether this is intentional or a bug but I have no idea. Why b2 tries to find a source file in a build directory?

**Comment by mloskot** [comment]
Smells like [Perforce Jam](https://www.perforce.com/documentation/jam-documentation) legacy.

**Comment by Kojoley** [comment]
Ok, it looks for it because it should be created by `make` rule:
```
t.write("dir/jamfile.jam", """\
import common ;
make hello1.cpp : hello.cpp : common.copy ;
""")
```
I see a message that `hello1.cpp` is copied and found `hello1.obj` in build directory but there is no `hello1.cpp`, it seems to be removed by b2 and afterwards it tries to scan its content, is not it a bug?

**Comment by Kojoley** [comment]
It is because the test is run with `-n Don't execute the commands, only print them` flag

**Pull request merged**
